version: "3"

tasks:
  default:
    cmds:
      - task: run
  run:
    desc: "run mock server"
    cmds:
      - go run cmd/main.go --config=./config/config_local.yaml
  test:
    desc: "Launch all tests"
    cmds:
      - go test ./tests -count=1 -v
  migrate:
    desc: "Run all migrations"
    cmds:
      - go run ./cmd/migrator --migrations-path=./migrations --direction=up
  unmigrate:
    desc: "Unrun all migrations"
    cmds:
      - go run ./cmd/migrator --migrations-path=./migrations --direction=down
