/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutStubsRouteImport } from './routes/about.stubs'
import { Route as AboutOverviewRouteImport } from './routes/about.overview'
import { Route as AboutComparisonRouteImport } from './routes/about.comparison'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProjectProjectIdRouteImport } from './routes/_authenticated/project.$projectId'
import { Route as AuthenticatedProjectProjectIdVariablesRouteImport } from './routes/_authenticated/project_.$projectId.variables'
import { Route as AuthenticatedProjectProjectIdRestStubsRouteImport } from './routes/_authenticated/project_.$projectId.rest.stubs'
import { Route as AuthenticatedProjectProjectIdRestStubsCreateRouteImport } from './routes/_authenticated/project_.$projectId.rest.stubs_.create'
import { Route as AuthenticatedProjectProjectIdRestStubsStubIdRouteImport } from './routes/_authenticated/project_.$projectId.rest.stubs_.$stubId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutStubsRoute = AboutStubsRouteImport.update({
  id: '/stubs',
  path: '/stubs',
  getParentRoute: () => AboutRoute,
} as any)
const AboutOverviewRoute = AboutOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AboutRoute,
} as any)
const AboutComparisonRoute = AboutComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => AboutRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectProjectIdRoute =
  AuthenticatedProjectProjectIdRouteImport.update({
    id: '/project/$projectId',
    path: '/project/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectProjectIdVariablesRoute =
  AuthenticatedProjectProjectIdVariablesRouteImport.update({
    id: '/project_/$projectId/variables',
    path: '/project/$projectId/variables',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectProjectIdRestStubsRoute =
  AuthenticatedProjectProjectIdRestStubsRouteImport.update({
    id: '/project_/$projectId/rest/stubs',
    path: '/project/$projectId/rest/stubs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectProjectIdRestStubsCreateRoute =
  AuthenticatedProjectProjectIdRestStubsCreateRouteImport.update({
    id: '/project_/$projectId/rest/stubs_/create',
    path: '/project/$projectId/rest/stubs/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectProjectIdRestStubsStubIdRoute =
  AuthenticatedProjectProjectIdRestStubsStubIdRouteImport.update({
    id: '/project_/$projectId/rest/stubs_/$stubId',
    path: '/project/$projectId/rest/stubs/$stubId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/about/comparison': typeof AboutComparisonRoute
  '/about/overview': typeof AboutOverviewRoute
  '/about/stubs': typeof AboutStubsRoute
  '/project/$projectId': typeof AuthenticatedProjectProjectIdRoute
  '/project/$projectId/variables': typeof AuthenticatedProjectProjectIdVariablesRoute
  '/project/$projectId/rest/stubs': typeof AuthenticatedProjectProjectIdRestStubsRoute
  '/project/$projectId/rest/stubs/$stubId': typeof AuthenticatedProjectProjectIdRestStubsStubIdRoute
  '/project/$projectId/rest/stubs/create': typeof AuthenticatedProjectProjectIdRestStubsCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/about/comparison': typeof AboutComparisonRoute
  '/about/overview': typeof AboutOverviewRoute
  '/about/stubs': typeof AboutStubsRoute
  '/project/$projectId': typeof AuthenticatedProjectProjectIdRoute
  '/project/$projectId/variables': typeof AuthenticatedProjectProjectIdVariablesRoute
  '/project/$projectId/rest/stubs': typeof AuthenticatedProjectProjectIdRestStubsRoute
  '/project/$projectId/rest/stubs/$stubId': typeof AuthenticatedProjectProjectIdRestStubsStubIdRoute
  '/project/$projectId/rest/stubs/create': typeof AuthenticatedProjectProjectIdRestStubsCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/about/comparison': typeof AboutComparisonRoute
  '/about/overview': typeof AboutOverviewRoute
  '/about/stubs': typeof AboutStubsRoute
  '/_authenticated/project/$projectId': typeof AuthenticatedProjectProjectIdRoute
  '/_authenticated/project_/$projectId/variables': typeof AuthenticatedProjectProjectIdVariablesRoute
  '/_authenticated/project_/$projectId/rest/stubs': typeof AuthenticatedProjectProjectIdRestStubsRoute
  '/_authenticated/project_/$projectId/rest/stubs_/$stubId': typeof AuthenticatedProjectProjectIdRestStubsStubIdRoute
  '/_authenticated/project_/$projectId/rest/stubs_/create': typeof AuthenticatedProjectProjectIdRestStubsCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/dashboard'
    | '/projects'
    | '/about/comparison'
    | '/about/overview'
    | '/about/stubs'
    | '/project/$projectId'
    | '/project/$projectId/variables'
    | '/project/$projectId/rest/stubs'
    | '/project/$projectId/rest/stubs/$stubId'
    | '/project/$projectId/rest/stubs/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/dashboard'
    | '/projects'
    | '/about/comparison'
    | '/about/overview'
    | '/about/stubs'
    | '/project/$projectId'
    | '/project/$projectId/variables'
    | '/project/$projectId/rest/stubs'
    | '/project/$projectId/rest/stubs/$stubId'
    | '/project/$projectId/rest/stubs/create'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/projects'
    | '/about/comparison'
    | '/about/overview'
    | '/about/stubs'
    | '/_authenticated/project/$projectId'
    | '/_authenticated/project_/$projectId/variables'
    | '/_authenticated/project_/$projectId/rest/stubs'
    | '/_authenticated/project_/$projectId/rest/stubs_/$stubId'
    | '/_authenticated/project_/$projectId/rest/stubs_/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/stubs': {
      id: '/about/stubs'
      path: '/stubs'
      fullPath: '/about/stubs'
      preLoaderRoute: typeof AboutStubsRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/overview': {
      id: '/about/overview'
      path: '/overview'
      fullPath: '/about/overview'
      preLoaderRoute: typeof AboutOverviewRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/comparison': {
      id: '/about/comparison'
      path: '/comparison'
      fullPath: '/about/comparison'
      preLoaderRoute: typeof AboutComparisonRouteImport
      parentRoute: typeof AboutRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project/$projectId': {
      id: '/_authenticated/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project_/$projectId/variables': {
      id: '/_authenticated/project_/$projectId/variables'
      path: '/project/$projectId/variables'
      fullPath: '/project/$projectId/variables'
      preLoaderRoute: typeof AuthenticatedProjectProjectIdVariablesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project_/$projectId/rest/stubs': {
      id: '/_authenticated/project_/$projectId/rest/stubs'
      path: '/project/$projectId/rest/stubs'
      fullPath: '/project/$projectId/rest/stubs'
      preLoaderRoute: typeof AuthenticatedProjectProjectIdRestStubsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project_/$projectId/rest/stubs_/create': {
      id: '/_authenticated/project_/$projectId/rest/stubs_/create'
      path: '/project/$projectId/rest/stubs/create'
      fullPath: '/project/$projectId/rest/stubs/create'
      preLoaderRoute: typeof AuthenticatedProjectProjectIdRestStubsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project_/$projectId/rest/stubs_/$stubId': {
      id: '/_authenticated/project_/$projectId/rest/stubs_/$stubId'
      path: '/project/$projectId/rest/stubs/$stubId'
      fullPath: '/project/$projectId/rest/stubs/$stubId'
      preLoaderRoute: typeof AuthenticatedProjectProjectIdRestStubsStubIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedProjectProjectIdRoute: typeof AuthenticatedProjectProjectIdRoute
  AuthenticatedProjectProjectIdVariablesRoute: typeof AuthenticatedProjectProjectIdVariablesRoute
  AuthenticatedProjectProjectIdRestStubsRoute: typeof AuthenticatedProjectProjectIdRestStubsRoute
  AuthenticatedProjectProjectIdRestStubsStubIdRoute: typeof AuthenticatedProjectProjectIdRestStubsStubIdRoute
  AuthenticatedProjectProjectIdRestStubsCreateRoute: typeof AuthenticatedProjectProjectIdRestStubsCreateRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedProjectProjectIdRoute: AuthenticatedProjectProjectIdRoute,
  AuthenticatedProjectProjectIdVariablesRoute:
    AuthenticatedProjectProjectIdVariablesRoute,
  AuthenticatedProjectProjectIdRestStubsRoute:
    AuthenticatedProjectProjectIdRestStubsRoute,
  AuthenticatedProjectProjectIdRestStubsStubIdRoute:
    AuthenticatedProjectProjectIdRestStubsStubIdRoute,
  AuthenticatedProjectProjectIdRestStubsCreateRoute:
    AuthenticatedProjectProjectIdRestStubsCreateRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AboutRouteChildren {
  AboutComparisonRoute: typeof AboutComparisonRoute
  AboutOverviewRoute: typeof AboutOverviewRoute
  AboutStubsRoute: typeof AboutStubsRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutComparisonRoute: AboutComparisonRoute,
  AboutOverviewRoute: AboutOverviewRoute,
  AboutStubsRoute: AboutStubsRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
