/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectProjectIdRouteImport } from './routes/project.$projectId'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as ProjectProjectIdRestStubsRouteImport } from './routes/project_.$projectId.rest.stubs'
import { Route as ProjectProjectIdRestStubsCreateRouteImport } from './routes/project_.$projectId.rest.stubs_.create'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ProjectProjectIdRestStubsRoute =
  ProjectProjectIdRestStubsRouteImport.update({
    id: '/project_/$projectId/rest/stubs',
    path: '/project/$projectId/rest/stubs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectProjectIdRestStubsCreateRoute =
  ProjectProjectIdRestStubsCreateRouteImport.update({
    id: '/project_/$projectId/rest/stubs_/create',
    path: '/project/$projectId/rest/stubs/create',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/about': typeof AuthenticatedAboutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/project/$projectId/rest/stubs': typeof ProjectProjectIdRestStubsRoute
  '/project/$projectId/rest/stubs/create': typeof ProjectProjectIdRestStubsCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/about': typeof AuthenticatedAboutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/project/$projectId/rest/stubs': typeof ProjectProjectIdRestStubsRoute
  '/project/$projectId/rest/stubs/create': typeof ProjectProjectIdRestStubsCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/project_/$projectId/rest/stubs': typeof ProjectProjectIdRestStubsRoute
  '/project_/$projectId/rest/stubs_/create': typeof ProjectProjectIdRestStubsCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/projects'
    | '/about'
    | '/dashboard'
    | '/project/$projectId'
    | '/project/$projectId/rest/stubs'
    | '/project/$projectId/rest/stubs/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/projects'
    | '/about'
    | '/dashboard'
    | '/project/$projectId'
    | '/project/$projectId/rest/stubs'
    | '/project/$projectId/rest/stubs/create'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/projects'
    | '/_authenticated/about'
    | '/_authenticated/dashboard'
    | '/project/$projectId'
    | '/project_/$projectId/rest/stubs'
    | '/project_/$projectId/rest/stubs_/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRoute
  ProjectProjectIdRestStubsRoute: typeof ProjectProjectIdRestStubsRoute
  ProjectProjectIdRestStubsCreateRoute: typeof ProjectProjectIdRestStubsCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/project_/$projectId/rest/stubs': {
      id: '/project_/$projectId/rest/stubs'
      path: '/project/$projectId/rest/stubs'
      fullPath: '/project/$projectId/rest/stubs'
      preLoaderRoute: typeof ProjectProjectIdRestStubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project_/$projectId/rest/stubs_/create': {
      id: '/project_/$projectId/rest/stubs_/create'
      path: '/project/$projectId/rest/stubs/create'
      fullPath: '/project/$projectId/rest/stubs/create'
      preLoaderRoute: typeof ProjectProjectIdRestStubsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRoute,
  ProjectProjectIdRoute: ProjectProjectIdRoute,
  ProjectProjectIdRestStubsRoute: ProjectProjectIdRestStubsRoute,
  ProjectProjectIdRestStubsCreateRoute: ProjectProjectIdRestStubsCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
